---
- name: EOS L2 Hybrid (Complete Dynamic Style)
  hosts: all
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Wait for eAPI port 443 to be active
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 443
        delay: 10      # 至少等 10 秒再开始检测
        timeout: 300   # 最多等 5 分钟
      delegate_to: localhost

    - name: Create VLANs
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
        state: merged
      loop: "{{ vlans | default([]) }}"

    #    - name: 1. Set physical interfaces to Layer2
    #      arista.eos.eos_interfaces:
    #        config:
    #          - name: "{{ item }}"
    #            mode: layer2
    #        state: merged
    #      loop: "{{ interfaces | default([]) }}"

    # ==================================================
    # 2. 批量创建 LAG 成员关系
    # ==================================================
    - name: 2. Bind members to multiple Port-Channels
      arista.eos.eos_lag_interfaces:
        config:
          - name: "{{ item.0.name }}"
            members:
              - member: "{{ item.1 }}"
                mode: active
        state: merged
      with_subelements:
        - "{{ lags | default([]) }}"
        - members

    - name: Force L2 on Port-Channel
      arista.eos.eos_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: layer2
        state: merged
      loop: "{{ lags | default([]) }}"
    # ==================================================
    # 3. 批量配置所有聚合口为 Trunk
    # ==================================================
    - name: 3. Configure all Port-Channel Trunks
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            trunk:
              trunk_allowed_vlans: "{{ item.vlans }}"
        state: merged
      loop: "{{ lags | default([]) }}"

    # ==================================================
    # 4. 配置 Access 端口
    # ==================================================
    - name: 4a. Force Layer2 Mode
      arista.eos.eos_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: layer2
        state: merged
      loop: "{{ access_ports | default([]) }}"

    - name: 4. Configure Access VLANs
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            access:
              vlan: "{{ item.vlan }}"
        state: merged
      loop: "{{ access_ports | default([]) }}"

    - name: Disable ZeroTouch to allow saving
      arista.eos.eos_config:
        lines:
          - zerotouch disable
      # 忽略错误，因为如果 ZTP 已经禁用了，这条命令可能会报错
      ignore_errors: yes
    # ==================================================
    # 5. 保存配置
    # ==================================================
    - name: 5. Save Configuration
      arista.eos.eos_config:
        save_when: modified